---
apiVersion: v1
kind: Service
metadata:
  name: authz
  labels:
    app: authz
spec:
  ports:
    - name: remote-authz
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: authz-control
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: authz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authz
spec:
  selector:
    matchLabels:
      app: authz
  replicas: 1
  template:
    metadata:
      labels:
        app: authz
    spec:
      containers:
        - name: authz
          image: kettil/kram-auth
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          ports:
            - containerPort: 8080
            - containerPort: 8081
